### ISSUE TITLE
missing support for 3gxloader luma 10.2.1

### ISSUE THREAD

**Issue by radostin04** [DarkFlare69/MK7-Online-NTR-Plugin-v3#7]
title. people have been screaming at us that the plugin doesn't work so an update would be appreciated

**Comment by SuperGamingBros4** [comment]
I think that they need to update the plugin loader to support older plugins. Because all older plugins are broken and give the same error, but I agree this plugin needs to be updated.

**Comment by DarkFlare69** [comment]
This issue was addressed in the top post on the GBAtemp thread: https://gbatemp.net/threads/release-mario-kart-7-online-ntr-plugin.460631/page-23

The library/template to support the 10.2.1 plugin loader is not publicly available. In order to update my plugin, it requires the latest template. I'm keeping this issue open because I'm more than willing to update my plugin if someone can provide me with a proper template, but until that happens, this plugin cannot be updated.

**Comment by DarkFlare69** [comment]
This issue has been resolved. Support for Luma plugin loader v10.2.1 has been added. Please check the release here: https://github.com/DarkFlare69/MK7-Online-NTR-Plugin-v3/releases/tag/v3.8.4
